### ISSUE TITLE
build of trizen fails in the vmware environement

### ISSUE THREAD

**Issue by Chr0nos** [Chr0nos/jarvis#5]
i'l do more tests and put more informations tonight
this works with the following test case,

```python
from arch import ArchInstall, ArchUser
from mock import patch

def donothink(path):
    pass

@patch("os.chroot", side_effect=donothink)
def run(_):
    arch = ArchInstall(mnt="/", hostname="StarK")
    user = ArchUser(arch, username="adamaru", uid=1000, gid=1000)
    user.install_trizen()

if __name__ == "__main__":
    run()
```

**Comment by Chr0nos** [comment]
```
Adding user adamaru to group audio
Adding user adamaru to group video
Adding user adamaru to group lp
Adding user adamaru to group wheel
Adding user adamaru to group scanner
Adding user adamaru to group render
Adding user adamaru to group input
Adding user adamaru to group games
uid=1000(adamaru) gid=1000(adamaru) groups=1000(adamaru),0(root),1(bin),2(daemon),3(sys),4,6,10,19(log)
Cloning into '/home/adamaru/trizen'...
remote: Enumerating objects: 248, done.
remote: Counting objects: 100% (248/248), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 248 (delta 73), reused 246 (delta 73)
Receiving objects: 100% (248/248), 43.25 KiB | 651.00 KiB/s, done.
Resolving deltas: 100% (73/73), done.
/home/adamaru/trizen
==> Making package: trizen 1:1.58-1 (Mon Mar 25 18:13:41 2019)
==> Checking runtime dependencies...
==> Installing missing dependencies...

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

adamaru is not in the sudoers file.  This incident will be reported.
==> ERROR: 'pacman' failed to install missing dependencies.
Traceback (most recent call last):
  File "./install_json.py", line 121, in <module>
    install_from_json(sys.argv[1])
  File "./install_json.py", line 95, in install_from_json
    handle_users(arch, config.get('users', []))
  File "./install_json.py", line 36, in handle_users
    user.install_trizen()
  File "/home/adamaru/projets/jarvis/scripts/archinstall/arch/archuser.py", line 98, in install_trizen
    self.run(['makepkg', '-sic', '--noconfirm'], cwd=trizen_path)
  File "/home/adamaru/projets/jarvis/scripts/archinstall/arch/archuser.py", line 42, in run
    self.runner.run(command, capture=False, preexec_fn=self.demote, **kwargs)
  File "/home/adamaru/projets/jarvis/scripts/archinstall/arch/runner.py", line 22, in run
    raise CommandFail(command)
arch.exceptions.CommandFail: ['makepkg', '-sic', '--noconfirm']
```

**Comment by Chr0nos** [comment]
fixed with os.setgroups
